# Generated by Django 2.0 on 2020-12-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.CharField(max_length=7)),
                ('Specification', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Dismantle', models.CharField(max_length=10)),
                ('Counts', models.FloatField(null=True)),
                ('Unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID', models.CharField(max_length=10)),
                ('ContractName', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetM.Contract'),
        ),
    ]
