# Generated by Django 2.0 on 2020-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access',
            new_name='BudgetAccess',
        ),
    ]
